##
## EPITECH PROJECT, 2021
## B-OOP-400-STG-4-1-arcade-quentin.pages
## File description:
## Makefile
##

all: 
	make -C ./Ncurses/
	make -C ./Sdl2/
	make -C ./SFML/

clean:
	make clean -C ./Ncurses/
	make clean -C ./Sdl2/
	make clean -C ./SFML/

fclean:
	make fclean -C ./Ncurses/
	make fclean -C ./Sdl2/
	make fclean -C ./SFML/

re:
	make re -C ./Ncurses/
	make re -C ./Sdl2/
	make re -C ./SFML/