##
## EPITECH PROJECT, 2021
## B-OOP-400-STG-4-1-arcade-quentin.pages
## File description:
## Makefile
##

all:
	make -C ./Nibbler/
	make -C ./Pacman/

clean:
	make clean -C ./Nibbler/
	make clean -C ./Pacman/

fclean:
	make fclean -C ./Nibbler/
	make fclean -C ./Pacman/

re:
	make re -C ./Nibbler/
	make re -C ./Pacman/